BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id BIGSERIAL,
    name VARCHAR(180) NULL DEFAULT NULL,
    email VARCHAR(135) NULL DEFAULT NULL,
    password VARCHAR(255) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,	
    PRIMARY KEY (id)
);
END;